### ISSUE TITLE
Sickrage

### ISSUE THREAD

**Issue by faldo7777** [lsellens/script.module.audo-programs#5]
Hi .. don't seem to be able to access the web interface on Sickrage after the 0.1.4 update .. this is on Cubox iMx6 with openelec 5.95.5

**Comment by ramonskie** [comment]
same issue here also on cubox with openelec  5.0.8

sickbeard and coucpotato webui are down

can't find any strange things in the logs though

**Comment by faldo7777** [comment]
also tried on osmc october update and has the same issue on Raspberry Pi 2

**Comment by lsellens** [comment]
Could you post a debug log please

**Comment by faldo7777** [comment]
Sorry I work away so won't be able to do this until weekend .. also no idea
where to find the logs

**Comment by ramonskie** [comment]
@lsellens can you tell me where i can set the debug logging?
because i don't see sickrage even starting up

and is there the ability to stop/start the service?

**Comment by lsellens** [comment]
http://kodi.wiki/view/Log_file

**Comment by ramonskie** [comment]
http://xbmclogs.com/pvlzomx8d

**Comment by ramonskie** [comment]
is there a way to rollback without setting all the settings over again in couch and sickrage

**Comment by lsellens** [comment]
Yes, all of the settings are in should stay even if you roll back a version with the addon manager. Nothing pops out at me in your log and I don't have an IMx6 myself to do any testing. Is there anything in your sickrage or couchpotato logs? They are in /storage/.kodi/userdata/addon_data/script.service.audo/logs
All of your settings files are here as well.

**Comment by ramonskie** [comment]
i don't have the option for rollback in kodi
so how can i install the previous version
because if i delete the current audo
and install it again it will install the latest.

i have tried to do by installing the zip in
https://github.com/lsellens/script.service.audo/releases

but then i get the warning that it does not have the right structure

**Comment by faldo7777** [comment]
Just to say I tried this version on the IMX6 and a raspberry Pi 2 and both
had the same issue and the previous version of the programs worked fine

**Comment by ramonskie** [comment]
deleted 
- /storage/.kodi/addons/script.module.audo*
- /storage/.kodi/addons/script.service.audo/

rebooted 
and downloaded and installed the following version from zip file in the following order
from http://lsellens.openelec.tv/addons/repo/
- script.module.audo-dependencies-0.0.9
- script.module.audo-programs-0.1.3
- script.module.audo-0.0.4
- script.service.audo-1.1.9

i hope this information helps

o and you don't need to delete /storage/.kodi/userdata/addon_data/script.service.audo

**Comment by lsellens** [comment]
before you roll back if you don't mind sending me the logs for sickbeard and couchpotato I would love to fix the actual issue.

**Comment by cjgreen** [comment]
I have been experiencing the same problems on my CuBox-i since the last update. Sickrage, Couchpotato and Headphones are no longer working. I spent a while looking at the logs and debugging. The logs don't appear to show anything out of the ordinary.

I moved all my existing logs from .kodi/userdata/addon_data/script.service.audo/logs/ into .kodi/userdata/addon_data/script.service.audo/logs/archive/ and reboot my machine so I could get fresh logs. Below are the results.

.kodi/temp/kodi.log:
http://xbmclogs.com/p0nc7nn3w

.kodi/userdata/addon_data/script.service.audo/logs/CouchPotato.log:
http://xbmclogs.com/p5lzggi7h

.kodi/userdata/addon_data/script.service.audo/logs/error.log:
Empty

.kodi/userdata/addon_data/script.service.audo/logs/sickrage.log:
Not generated

.kodi/userdata/addon_data/script.service.audo/logs/headphones.log:
Not generated

Some interesting things to take note from my debugging: 
- I ran a watch on ps aux | grep audo to check if the services actually started and they did, however Sickrage, Couchpotato and Headphones all stopped after a couple of seconds.
- A very interesting thing to note is that Sickrage ran when I manually executed it via command line using the same command line that audo was calling `python /storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/SickBeard.py --daemon --datadir /storage/.kodi/userdata/addon_data/script.service.audo/ --pidfile=/var
  /run/sickbeard.pid --config /storage/.kodi/userdata/addon_data/script.service.audo/sickbeard.ini`
- I tried changing the function in .kodi/addons/script.service.audo/resources/audo.py that starts Sickrage from subprocess.call to subprocess.check_output so I could log the python scripts stout and sderr but either I was doing it wrong or both of those were returning nothing.. 

I am happy to help out with some more debugging as I would like to fix this on my own machine.

**Comment by ramonskie** [comment]
is this solved because i see there are newer releases now

**Comment by cjgreen** [comment]
@ramonskie I have updated to OpenELEC (official) Version: 6.0.1 and script.module.audo-programs version 0.2.3 and I am still experiencing the issue.

**Comment by ramonskie** [comment]
nothing changed indeed
i created a startup script for sickbeard/couchpotato

**Comment by ramonskie** [comment]
@lsellens this issue still exists to this day any news on it?

**Comment by lsellens** [comment]
This should be fixed in current version. Please reopen if problem persists.
